### ISSUE TITLE
Is PySimpleGUI poorly documented?

### ISSUE THREAD

**Issue by PySimpleGUI** [mo-han/mo-han-toolbox#1]
Concerned that I see PySimpleGUI in your list.   There is a TON of documentation written for it.  Is there a reason it made the list?  If so, I would like to work on fixing that as it's meant to be easily usable because of several documents and 100's of demo programs.  Let me know what else can be done so that it's not on your list.

**Comment by mo-han** [comment]
No I mean the code written by ME is all poorly documented because those scripts or apps are just my self-using toolkit.

**Comment by PySimpleGUI** [comment]
LOL... I'm sorry about the misunderstanding.  Just trying to make sure PySimpleGUI is well documented and no misunderstandings.  If **_anyone_** is struggling, I want to try and help.  Sorry about the mixup.  I'm not sure they need to be documented.  Most PySimpleGUI programs are easy enough to understand they don't need many comments.

There was just a big change made to all demos and the docs are being changed too.  Instead of testing for window closed being `event is None` the new test is `event == WIN_CLOSED`.  This makes it even more obvious to beginner what is being tested.

I hope you enjoyed using PySimpleGUI.
