### ISSUE TITLE
 mo-han-toolbox/etc/clash/rule.js报错

### ISSUE THREAD

**Issue by LethargyTeddy** [mo-han/mo-han-toolbox#3]
![截图_2023-01-11_23-15-21](https://user-images.githubusercontent.com/52397629/211843338-cce7139d-5d9c-4049-aacd-581e8b16f9bb.png)
大佬这个该怎么改啊？

**Comment by mo-han** [comment]
我用的是https://github.com/zzzgydi/clash-verge/
这个·配置文件是个javascript脚本，用来修改yaml中的配置的，你用的客户端应该是不支持这种脚本吧

**Comment by LethargyTeddy** [comment]
哦哦好的，我用的是cfw。

**Comment by LethargyTeddy** [comment]
> 我用的是https://github.com/zzzgydi/clash-verge/ 这个·配置文件是个javascript脚本，用来修改yaml中的配置的，你用的客户端应该是不支持这种脚本吧

大佬有clash或cfw的配置yaml吗？

**Comment by LethargyTeddy** [comment]
> 我用的是https://github.com/zzzgydi/clash-verge/ 这个·配置文件是个javascript脚本，用来修改yaml中的配置的，你用的客户端应该是不支持这种脚本吧
![无标题1](https://user-images.githubusercontent.com/52397629/212248098-3fd15985-e08c-4446-89e0-74493cee7800.png)
![无标题](https://user-images.githubusercontent.com/52397629/212248124-198656c7-ad19-4662-a047-8186d6fdc68f.png)
![无标题2](https://user-images.githubusercontent.com/52397629/212248131-85ed17c5-5f70-4135-9908-b5a6718595d6.png)
大佬，我把rule.yaml和rule.js导入了，rule.yanl可以启动，但是rule.js不能启动，这个是我的操作不对吗？还是要导入其他的文件？

**Comment by mo-han** [comment]
再加个订阅就行了吧，只要有节点，`rule.js`就能正常工作了。
我不是大佬，祝你用得开心。

**Comment by LethargyTeddy** [comment]
> 再加个订阅就行了吧，只要有节点，`rule.js`就能正常工作了。 我不是大佬，祝你用得开心。
订阅？？具体该怎么操作，您方便说下吗？

**Comment by mo-han** [comment]
你既然想用clash当然要在配置里添加节点啊，各种clash客户端的入门教程都会教，没有节点怎么用呢
