### ISSUE TITLE
rule.js和rule.yaml无法启动

### ISSUE THREAD

**Issue by LethargyTeddy** [mo-han/mo-han-toolbox#4]
![截图_2023-06-26_09-55-30](https://github.com/mo-han/mo-han-toolbox/assets/52397629/e37aa34a-f33e-4b63-a60f-0a36dbfb4467)
作者你好啊，在网上看到您写的脚本，想试一试，但是有点小问题，就是这俩个文件在右键点击启动之后完全没有任何反应，日志里面也没有任何信息，您有遇到过这种情况吗，该怎么解决啊？

**Comment by mo-han** [comment]
报错了日志里会有记录，不报错那就是启动成功，至于脚本运行效果，可以查看代理分组、设置里的运行配置。

**Comment by LethargyTeddy** [comment]
> 报错了日志里会有记录，不报错那就是启动成功，至于脚本运行效果，可以查看代理分组、设置里的运行配置。

哦哦，在运行配置中看到了，但是感觉好像rule.js文件并没有起作用
![image](https://github.com/mo-han/mo-han-toolbox/assets/52397629/ea105f36-2379-4790-99e6-0de581cb2325)
这里面没有出现select，url-test，fallback，direct这四个。

**Comment by mo-han** [comment]
看看配置页面截图呢。

**Comment by LethargyTeddy** [comment]
> 看看配置页面截图呢。
这是配置页面的截图：
![image](https://github.com/mo-han/mo-han-toolbox/assets/52397629/d122108c-892d-475d-aeff-86a34af0eb03)
这是运行配置的部分截图：
![image](https://github.com/mo-han/mo-han-toolbox/assets/52397629/aab7c104-622f-41fa-b5a6-ae6c0072793d)

**Comment by mo-han** [comment]
下面两个没有启用，启用的都是深色的，就和上面选中的配置一样

**Comment by LethargyTeddy** [comment]
> 下面两个没有启用，启用的都是深色的，就和上面选中的配置一样

嗯~ o(*￣▽￣*)o，右键启动后没有一点反应，日志也没输出，但是运行配置的内容确实变了，所以目前来看，只有rule.js文件没有启动。

**Comment by mo-han** [comment]
是说 rule.yaml 生效了？

我也更新到了最新版，确定能用。不过发现个以前没注意到的细节，这俩启动还得有个顺序。我这里是得要先开启 yaml merge，再开启 js script，完事还得把 js 移到末尾。

**Comment by LethargyTeddy** [comment]
> 是说 rule.yaml 生效了？
![无标题](https://github.com/mo-han/mo-han-toolbox/assets/52397629/66ab924c-00d6-46cc-bd24-d710236818fa)
是的

**Comment by LethargyTeddy** [comment]
> 

我的开启顺序和你正好相反，我得先开js，再开启yaml merge，不然连上面的效果都没了

**Comment by LethargyTeddy** [comment]
> 是说 rule.yaml 生效了？
> 
> 我也更新到了最新版，确定能用。不过发现个以前没注意到的细节，这俩启动还得有个顺序。我这里是得要先开启 yaml merge，再开启 js script，完事还得把 js 移到末尾。

哦哦，我找到病因了，是因为内核，clash内核不能用，得换成meta的内核才行

**Comment by LethargyTeddy** [comment]
> 是说 rule.yaml 生效了？
> 
> 我也更新到了最新版，确定能用。不过发现个以前没注意到的细节，这俩启动还得有个顺序。我这里是得要先开启 yaml merge，再开启 js script，完事还得把 js 移到末尾。

![image](https://github.com/mo-han/mo-han-toolbox/assets/52397629/80424063-1c7a-41ea-9b02-1fac442d18c8)
切换clash内核就会报错

**Comment by mo-han** [comment]
我正在用clash内核，应该是别的原因。先别管了，能用就先凑合用，以后会搞清楚的。

**Comment by LethargyTeddy** [comment]
> 我正在用clash内核，应该是别的原因。先别管了，能用就先凑合用，以后会搞清楚的。

https://github.com/mo-han/mo-han-toolbox/blob/0123b3a4ae1dbeae2105a1efa071bd7226d883bc/etc/clash/rule.yaml#L28
这个地方有一点小问题，开头的porxy,应该改成url

**Comment by mo-han** [comment]
https://github.com/mo-han/mo-han-toolbox/blob/0123b3a4ae1dbeae2105a1efa071bd7226d883bc/etc/clash/rule.yaml#L28
> 这个地方有一点小问题，开头的porxy,应该改成url

704db78bdcf25dc5e8dd2a095b4327cca255de60 改好惹
